[package]
name = "imap-client"
version = "0.1.4"
description = "Rust library to manage IMAP clients"
homepage = "https://github.com/soywod/imap-client"
documentation = "https://docs.rs/imap-client/latest/imap_client/"
repository = "https://github.com/soywod/imap-client"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email"]
keywords = ["email", "imap", "client"]

[dev-dependencies]
static_assertions = "1.1.0"
tokio = { version = "1.37.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dependencies]
imap-next = { version = "0.2.0", features = ["expose_stream", "tag_generator", "starttls", "ext_id", "ext_metadata", "rustls_ring"] }
once_cell = "1"
rustls-native-certs = "0.7.0"
thiserror = "1.0.50"
tokio = { version = "1.37.0", features = ["net", "time"] }
tokio-rustls = { version = "0.26.0", default-features = false, features = ["logging", "tls12", "ring"] }
tracing = "0.1.40"

[patch.crates-io]
imap-codec = { git = "https://github.com/duesee/imap-codec" }
imap-next = { git = "https://github.com/soywod/imap-next" }
# imap-next = { path = "/home/soywod/code/imap-next" }
